{
  config,
  pkgs,
  inputs,
  lib,
  nixvim,
  outputs,
  nixpkgs-unstable,
  ...
}: {
  home.stateVersion = "24.05";
  # list of programs
  # https://mipmip.github.io/home-manager-option-search
  imports = [
    ./../modules/nvim
    ./../modules/alacritty
    #		./../modules/eww
  ];
 # programs.nixvim = {
 #   enable = true;
  #    colorschemes.gruvbox.enable = true;
  #    plugins.lightline.enable = true;
 # };

  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };

  programs.fzf = {
    enable = true;
    enableZshIntegration = true;
    tmux.enableShellIntegration = true;
  };

  programs.git = {
    enable = true;
    lfs.enable = true;
    settings = {
      user.name = "Justin Gilpin";
			user.email = "justin.lee.gilpin@gmail.com";
      init = {defaultBranch = "master";};
      merge = {
        conflictStyle = "diff3";
        tool = "meld";
      };
      pull = {rebase = false;};
    };
  }; # end git

  programs.diff-so-fancy = {
    enable = true;
    enableGitIntegration = true;
  };

  # Source Dot Files
  # hyprland.conf is now generated by wayland.windowManager.hyprland.settings
  # in modules/wm/hyprland/default.nix — no symlink needed here.
  home.file.".config/hypr/hypridle.conf".source = ./../modules/hyprland/hypridle.conf;
  home.file.".config/hypr/hyprlock.conf".source = ./../modules/hyprland/hyprlock.conf;
  home.file.".config/hypr/hyprpaper.conf".source = ./../modules/hyprland/hyprpaper.conf;
  # Waybar style — enable/systemd settings live in modules/basic/default.nix
  # so waybar is only active when the basic module is loaded.
  programs.waybar.style = builtins.readFile ./../modules/waybar/style.css;
  home.file.".config/waybar/config".source = ./../modules/waybar/config;

  # Override waybar service to add restart delay and remove restart limit.
  # Without this, rapid crash loops on startup lock the service into failed
  # state permanently and it won't start on next Hyprland login.
  systemd.user.services.waybar = {
    Service = {
      RestartSec = "3s";
    };
    Unit = {
      StartLimitIntervalSec = 0;
    };
  };

  # hyprland-session.target: activated by exec-once in hyprland.conf
  # BindsTo graphical-session.target so dependent services get proper ordering
  systemd.user.targets.hyprland-session = {
    Unit = {
      Description = "Hyprland compositor session";
      BindsTo = [ "graphical-session.target" ];
      Wants = [ "graphical-session-pre.target" ];
      After = [ "graphical-session-pre.target" ];
    };
  };
  # Test file to see if home-manager is working
  home.file.".config/test-home-manager.txt".text = "Home manager is working!";

  #  programs.firefox = {
  #    enable = true;
  #    profiles.justin = {
  #      extensions = with inputs.firefox-addons.packages."x86_64-linux"; [
  #        bitwarden
  #	ublock-origin
  #	sponsorblock
  #	darkreader
  #	tridactyl
  #	youtube-shorts-block
  #      ];
  #    };
  #  };

  programs.htop = {
    enable = true;
    settings.show_program_path = true;
  };

  # Make "discord" command and any Discord desktop launcher open Vesktop instead
  home.packages = with pkgs; [
    (pkgs.writeShellScriptBin "discord" ''exec vesktop "$@"'')
  ];

  # Discord icon — used by the desktop entry and as a vesktop icon override
  # Overriding hicolor/vesktop.png makes the tray show Discord's logo instead of Vesktop's
  home.file.".local/share/icons/discord.png".source =
    "${pkgs.discord}/share/icons/hicolor/256x256/apps/discord.png";
  home.file.".local/share/icons/hicolor/256x256/apps/vesktop.png".source =
    "${pkgs.discord}/share/icons/hicolor/256x256/apps/discord.png";

  # Desktop entry: searching "Discord" in the launcher opens Vesktop with Discord's icon
  xdg.desktopEntries.discord = {
    name = "Discord";
    exec = "vesktop %U";
    icon = "/home/justin/.local/share/icons/discord.png";
    comment = "All-in-one voice and text chat (via Vesktop)";
    categories = [ "Network" "InstantMessaging" ];
    mimeType = [ "x-scheme-handler/discord" ];
  };

  # Pywalfox — native messenger for Firefox theming via Noctalia
  # The extension must be installed in Firefox manually (search "Pywalfox" in add-ons)
  programs.firefox = {
    enable = true;
    nativeMessagingHosts = [ pkgs.pywalfox-native ];
  };

  # Kitty — theme comes from Noctalia's template engine
  # (writes ~/.config/kitty/themes/noctalia.conf on color scheme changes)
  programs.kitty = {
    enable = true;
    extraConfig = ''
      include themes/noctalia.conf
    '';
  };

  # btop — use the theme written by Noctalia's template engine
  programs.btop = {
    enable = true;
    settings = {
      color_theme = "noctalia";
    };
  };

  programs.lf.enable = true;

  #  programs.tmux = {
  #    enable = true;
  #    #keyMode = "vi";
  #    clock24 = true;
  #    historyLimit = 10000;
  #    plugins = with pkgs.tmuxPlugins; [
  #      gruvbox
  #    ];
  #    extraConfig = ''
  #      new-session -s main
  #      bind-key -n C-a send-prefix
  #    '';
  #  };

  programs.zsh = {
    enable = true;
#    enableAutosuggestions = true; # old
    autosuggestion.enable = true; # new name change
    enableCompletion = true;
    initContent = lib.mkMerge [
      (lib.mkOrder 550 ''
        source ${pkgs.zsh-syntax-highlighting}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
        source ${pkgs.zsh-vi-mode}/share/zsh-vi-mode/zsh-vi-mode.zsh
      '')
      (builtins.readFile ./files/zshrc)
      ''
        ${pkgs.figurine}/bin/figurine -f "3d.flf" $HOST
      ''
    ];
    oh-my-zsh = {
      enable = true;
      #   theme = "robbyrussell";
      plugins = ["python"];
    };
  };

  # Default applications
  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "text/html"                = "firefox.desktop";
      "x-scheme-handler/http"   = "firefox.desktop";
      "x-scheme-handler/https"  = "firefox.desktop";
      "x-scheme-handler/ftp"    = "firefox.desktop";
      "x-scheme-handler/about"  = "firefox.desktop";
      "x-scheme-handler/unknown" = "firefox.desktop";
      "terminal"                = "kitty.desktop";
    };
  };

  programs.home-manager.enable = true;
  programs.nix-index.enable = true;
  programs.zoxide.enable = true;

  # Nicely reload system units when changing configs
  systemd.user.startServices = "sd-switch";

  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
    matchBlocks."*" = {
      extraOptions = {
        ForwardAgent = "no";
        ServerAliveInterval = "0";
        ServerAliveCountMax = "3";
        Compression = "no";
        AddKeysToAgent = "no";
        HashKnownHosts = "no";
        UserKnownHostsFile = "~/.ssh/known_hosts";
        ControlMaster = "no";
        ControlPath = "~/.ssh/master-%r@%n:%p";
        ControlPersist = "no";
      };
    };
    #  extraConfig = ''
    #  Host *
    #    StrictHostKeyChecking no
    #  '';
    #  matchBlocks = {
    # wd
    #    "dt deepthought" = {
    #      hostname = "10.42.0.42";
    #      user = "alex";
    #    };
    #    "a anton" = {
    #      hostname = "10.42.1.20";
    #      user = "root";
    #    };
    #    "bricktop" = {
    #      hostname = "10.42.1.80";
    #      user = "pi";
    #    };
    #  };
  };
}
