{
  config,
  pkgs,
  inputs,
  lib,
  nixvim,
  outputs,
  nixpkgs-unstable,
  ...
}: {
  home.stateVersion = "24.05";
  # list of programs
  # https://mipmip.github.io/home-manager-option-search
  imports = [
    ./../modules/nvim
    #		./../modules/eww
  ];
 # programs.nixvim = {
 #   enable = true;
  #    colorschemes.gruvbox.enable = true;
  #    plugins.lightline.enable = true;
 # };

  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
  };

  programs.fzf = {
    enable = true;
    enableZshIntegration = true;
    tmux.enableShellIntegration = true;
  };

  programs.git = {
    enable = true;
    lfs.enable = true;
    settings = {
      user.name = "Justin Gilpin";
			user.email = "justin.lee.gilpin@gmail.com";
      init = {defaultBranch = "master";};
      merge = {
        conflictStyle = "diff3";
        tool = "meld";
      };
      pull = {rebase = false;};
    };
  }; # end git

  programs.diff-so-fancy = {
    enable = true;
    enableGitIntegration = true;
  };

  # Source Dot Files
  # hyprland.conf is now generated by wayland.windowManager.hyprland.settings
  # in modules/wm/hyprland/default.nix — no symlink needed here.
  # hypridle.conf is set per machine type:
  #   desktop → hosts/common/pc/desktop.nix
  #   laptop  → hosts/common/pc/laptop/default.nix
  home.file."Pictures/Wallpapers" = {
    source = ./files/wallpapers;
    recursive = true;
  };

  home.file.".config/hypr/hyprlock.conf".source = ./../modules/hyprland/hyprlock.conf;
  home.file.".config/hypr/hyprpaper.conf".source = ./../modules/hyprland/hyprpaper.conf;
  # Waybar style — enable/systemd settings live in modules/basic/default.nix
  # so waybar is only active when the basic module is loaded.
  programs.waybar.style = builtins.readFile ./../modules/waybar/style.css;
  home.file.".config/waybar/config".source = ./../modules/waybar/config;

  # Override waybar service to add restart delay and remove restart limit.
  # Without this, rapid crash loops on startup lock the service into failed
  # state permanently and it won't start on next Hyprland login.
  systemd.user.services.waybar = {
    Service = {
      RestartSec = "3s";
    };
    Unit = {
      StartLimitIntervalSec = 0;
    };
  };

  # hyprland-session.target: activated by exec-once in hyprland.conf
  # BindsTo graphical-session.target so dependent services get proper ordering
  systemd.user.targets.hyprland-session = {
    Unit = {
      Description = "Hyprland compositor session";
      BindsTo = [ "graphical-session.target" ];
      Wants = [ "graphical-session-pre.target" ];
      After = [ "graphical-session-pre.target" ];
    };
  };
  # Test file to see if home-manager is working
  home.file.".config/test-home-manager.txt".text = "Home manager is working!";

  #  programs.firefox = {
  #    enable = true;
  #    profiles.justin = {
  #      extensions = with inputs.firefox-addons.packages."x86_64-linux"; [
  #        bitwarden
  #	ublock-origin
  #	sponsorblock
  #	darkreader
  #	tridactyl
  #	youtube-shorts-block
  #      ];
  #    };
  #  };


  # Make "discord" command and any Discord desktop launcher open Vesktop instead
  home.packages = with pkgs; [
    (pkgs.writeShellScriptBin "discord" ''exec vesktop "$@"'')
  ];

  # Discord icon — used by the desktop entry and as a vesktop icon override
  # Overriding hicolor/vesktop.png makes the tray show Discord's logo instead of Vesktop's
  home.file.".local/share/icons/discord.png".source =
    "${pkgs.discord}/share/icons/hicolor/256x256/apps/discord.png";
  home.file.".local/share/icons/hicolor/256x256/apps/vesktop.png".source =
    "${pkgs.discord}/share/icons/hicolor/256x256/apps/discord.png";

  # Desktop entry: searching "Discord" in the launcher opens Vesktop with Discord's icon
  xdg.desktopEntries.discord = {
    name = "Discord";
    exec = "vesktop %U";
    icon = "/home/justin/.local/share/icons/discord.png";
    comment = "All-in-one voice and text chat (via Vesktop)";
    categories = [ "Network" "InstantMessaging" ];
    mimeType = [ "x-scheme-handler/discord" ];
  };

  # Pywalfox — native messenger for Firefox theming via Noctalia
  # The extension must be installed in Firefox manually (search "Pywalfox" in add-ons)
  programs.firefox = {
    enable = true;
    nativeMessagingHosts = [ pkgs.pywalfox-native ];
  };

  # Kitty — primary terminal, replaces alacritty.
  # Theme comes from Noctalia's template engine
  # (writes ~/.config/kitty/themes/noctalia.conf on color scheme changes).
  programs.kitty = {
    enable = true;
    font = {
      name = "JetBrainsMono Nerd Font";
      size = 12;
    };
    settings = {
      scrollback_lines        = 10000;
      wheel_scroll_multiplier = 3;
      cursor_shape            = "block";
      hide_mouse_when_typing  = true;
      # Tabs
      tab_bar_style           = "powerline";
      tab_powerline_style     = "slanted";
    };
    extraConfig = ''
      # Colors — written by Noctalia's template engine on each palette change
      include themes/noctalia.conf
    '';
  };

  # btop — use the theme written by Noctalia's template engine
  programs.btop = {
    enable = true;
    settings = {
      color_theme = "noctalia";
    };
  };

  programs.yazi = {
    enable = true;
    enableZshIntegration = true;
    settings = {
      preview = {
        image_protocol = "kitty";
      };
    };
  };

  #  programs.tmux = {
  #    enable = true;
  #    #keyMode = "vi";
  #    clock24 = true;
  #    historyLimit = 10000;
  #    plugins = with pkgs.tmuxPlugins; [
  #      gruvbox
  #    ];
  #    extraConfig = ''
  #      new-session -s main
  #      bind-key -n C-a send-prefix
  #    '';
  #  };

  programs.zsh = {
    enable = true;
#    enableAutosuggestions = true; # old
    autosuggestion.enable = true; # new name change
    enableCompletion = true;
    initContent = lib.mkMerge [
      (lib.mkOrder 550 ''
        source ${pkgs.zsh-syntax-highlighting}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
        source ${pkgs.zsh-vi-mode}/share/zsh-vi-mode/zsh-vi-mode.zsh
      '')
      (builtins.readFile ./files/zshrc)
      ''
        ${pkgs.figurine}/bin/figurine -f "3d.flf" $HOST
      ''
    ];
    oh-my-zsh = {
      enable = true;
      #   theme = "robbyrussell";
      plugins = ["python"];
    };
  };

  # VSCode extensions — declared here so they survive a fresh machine rebuild.
  programs.vscode = {
    enable = true;
    profiles.default.extensions = with pkgs.vscode-extensions; [
      # ── Nixpkgs-managed (auto-installed on rebuild) ──────────────────────
      github.copilot
      github.copilot-chat
      ms-python.python
      ms-python.vscode-pylance
      ms-toolsai.jupyter
      ms-toolsai.jupyter-keymap
      ms-toolsai.jupyter-renderers
      ms-toolsai.vscode-jupyter-cell-tags
      ms-toolsai.vscode-jupyter-slideshow
      vscodevim.vim

      # ── NOT in nixpkgs — auto-installed via activation script below ─────
      # anthropic.claude-code, openai.chatgpt, noctalia.noctaliatheme, ms-python.debugpy
    ];
  };

  # Vesktop settings — trayIcon must be explicitly enabled for the tray icon to appear
  home.file.".config/vesktop/settings.json".text = builtins.toJSON {
    discordBranch    = "stable";
    minimizeToTray   = true;
    trayIcon         = true;
    arRPC            = true;
    splashColor      = "rgb(235, 219, 178)";
    splashBackground = "rgb(40, 40, 40)";
  };

  # Seed VS Code argv.json — writable copy so VS Code can update it,
  # but seeded from dotfiles on every rebuild. Only written if missing or outdated.
  home.activation.seedVscodeArgv = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "$HOME/.vscode"
    cp --no-preserve=mode ${./files/vscode/argv.json} "$HOME/.vscode/argv.json.new"
    if ! diff -q "$HOME/.vscode/argv.json.new" "$HOME/.vscode/argv.json" &>/dev/null; then
      mv "$HOME/.vscode/argv.json.new" "$HOME/.vscode/argv.json"
    else
      rm "$HOME/.vscode/argv.json.new"
    fi
  '';

  # Seed VS Code settings.json — writable copy so VS Code and extensions can
  # write to it freely. Seeded from dotfiles on rebuild; only overwrites if the
  # seed differs so GUI changes survive between rebuilds.
  home.activation.seedVscodeSettings = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    SETTINGS_DIR="$HOME/.config/Code/User"
    mkdir -p "$SETTINGS_DIR"
    cp --no-preserve=mode ${./files/vscode/settings.json} "$SETTINGS_DIR/settings.json.new"
    if ! diff -q "$SETTINGS_DIR/settings.json.new" "$SETTINGS_DIR/settings.json" &>/dev/null; then
      mv "$SETTINGS_DIR/settings.json.new" "$SETTINGS_DIR/settings.json"
    else
      rm "$SETTINGS_DIR/settings.json.new"
    fi
  '';

  # Seed Claude Code settings.json — writable copy so Claude can update it,
  # but seeded from dotfiles on every rebuild. Only written if missing or outdated.
  home.activation.seedClaudeSettings = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "$HOME/.claude"
    cp --no-preserve=mode ${./files/claude/settings.json} "$HOME/.claude/settings.json.new"
    if ! diff -q "$HOME/.claude/settings.json.new" "$HOME/.claude/settings.json" &>/dev/null; then
      mv "$HOME/.claude/settings.json.new" "$HOME/.claude/settings.json"
    else
      rm "$HOME/.claude/settings.json.new"
    fi
  '';

  # Register pywalfox native messaging host for Firefox.
  # home-manager's nativeMessagingHosts doesn't place the manifest correctly,
  # so we write it manually via activation.
  home.activation.registerPywalfox = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p "$HOME/.mozilla/native-messaging-hosts"
    cat > "$HOME/.mozilla/native-messaging-hosts/pywalfox.json" <<EOF
{
  "name": "pywalfox",
  "description": "Automatically theme your browser using the colors generated by Pywal",
  "path": "${pkgs.pywalfox-native}/bin/pywalfox",
  "type": "stdio",
  "allowed_extensions": [ "pywalfox@frewacom.org" ]
}
EOF
  '';

  # Auto-install VSCode extensions not available in nixpkgs.
  # Skips silently if already installed so rebuilds are fast.
  home.activation.installVscodeExtensions = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    if command -v code &>/dev/null; then
      for ext in \
        anthropic.claude-code \
        openai.chatgpt \
        noctalia.noctaliatheme \
        ms-python.debugpy; do
        code --install-extension "$ext" --force 2>/dev/null || true
      done
    fi
  '';

  # Default applications
  xdg.mimeApps = {
    enable = true;
    defaultApplications = {
      "text/html"                = "firefox.desktop";
      "x-scheme-handler/http"   = "firefox.desktop";
      "x-scheme-handler/https"  = "firefox.desktop";
      "x-scheme-handler/ftp"    = "firefox.desktop";
      "x-scheme-handler/about"  = "firefox.desktop";
      "x-scheme-handler/unknown" = "firefox.desktop";
      "terminal"                = "kitty.desktop";
    };
  };

  programs.home-manager.enable = true;
  programs.nix-index.enable = true;
  programs.zoxide.enable = true;

  # Nicely reload system units when changing configs
  systemd.user.startServices = "sd-switch";

  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
    matchBlocks."*" = {
      extraOptions = {
        ForwardAgent = "no";
        ServerAliveInterval = "0";
        ServerAliveCountMax = "3";
        Compression = "no";
        AddKeysToAgent = "no";
        HashKnownHosts = "no";
        UserKnownHostsFile = "~/.ssh/known_hosts";
        ControlMaster = "no";
        ControlPath = "~/.ssh/master-%r@%n:%p";
        ControlPersist = "no";
      };
    };
    matchBlocks."linode" = {
      user = "root";
    };
    #  extraConfig = ''
    #  Host *
    #    StrictHostKeyChecking no
    #  '';
    #  matchBlocks = {
    # wd
    #    "dt deepthought" = {
    #      hostname = "10.42.0.42";
    #      user = "alex";
    #    };
    #    "a anton" = {
    #      hostname = "10.42.1.20";
    #      user = "root";
    #    };
    #    "bricktop" = {
    #      hostname = "10.42.1.80";
    #      user = "pi";
    #    };
    #  };
  };
}
