-- Noctalia color theme for Neovim
-- Auto-generated by Noctalia's template engine — do not edit manually.
-- Source this file in your init.lua: require("themes.noctalia")

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") then vim.cmd("syntax reset") end
vim.g.colors_name = "noctalia"

local c = {
  bg          = "{{colors.surface.default.hex}}",
  bg_variant  = "{{colors.surface_variant.default.hex}}",
  fg          = "{{colors.on_surface.default.hex}}",
  fg_muted    = "{{colors.on_surface_variant.default.hex}}",
  primary     = "{{colors.primary.default.hex}}",
  secondary   = "{{colors.secondary.default.hex}}",
  tertiary    = "{{colors.tertiary.default.hex}}",
  error       = "{{colors.error.default.hex}}",
  outline     = "{{colors.outline.default.hex}}",
  on_primary  = "{{colors.on_primary.default.hex}}",
}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Editor chrome
hi("Normal",        { fg = c.fg,       bg = c.bg })
hi("NormalFloat",   { fg = c.fg,       bg = c.bg_variant })
hi("LineNr",        { fg = c.outline })
hi("CursorLine",    { bg = c.bg_variant })
hi("CursorLineNr",  { fg = c.primary,  bold = true })
hi("SignColumn",    { bg = c.bg })
hi("ColorColumn",   { bg = c.bg_variant })
hi("VertSplit",     { fg = c.outline })
hi("WinSeparator",  { fg = c.outline })
hi("StatusLine",    { fg = c.fg,       bg = c.bg_variant })
hi("StatusLineNC",  { fg = c.fg_muted, bg = c.bg_variant })
hi("Pmenu",         { fg = c.fg,       bg = c.bg_variant })
hi("PmenuSel",      { fg = c.on_primary, bg = c.primary })
hi("PmenuSbar",     { bg = c.bg_variant })
hi("PmenuThumb",    { bg = c.outline })

-- Selection / search
hi("Visual",        { bg = c.bg_variant })
hi("Search",        { fg = c.on_primary, bg = c.secondary })
hi("IncSearch",     { fg = c.on_primary, bg = c.primary })

-- Diagnostics
hi("DiagnosticError", { fg = c.error })
hi("DiagnosticWarn",  { fg = c.secondary })
hi("DiagnosticInfo",  { fg = c.tertiary })
hi("DiagnosticHint",  { fg = c.fg_muted })

-- Syntax
hi("Comment",     { fg = c.outline,   italic = true })
hi("Constant",    { fg = c.tertiary })
hi("String",      { fg = c.secondary })
hi("Identifier",  { fg = c.fg })
hi("Function",    { fg = c.primary })
hi("Statement",   { fg = c.primary,   bold = true })
hi("Keyword",     { fg = c.primary,   bold = true })
hi("Operator",    { fg = c.fg_muted })
hi("Type",        { fg = c.tertiary })
hi("Special",     { fg = c.secondary })
hi("PreProc",     { fg = c.tertiary })
hi("Error",       { fg = c.error })
hi("Todo",        { fg = c.on_primary, bg = c.secondary, bold = true })

-- Treesitter (links to base groups, overrides where needed)
hi("@variable",           { fg = c.fg })
hi("@variable.builtin",   { fg = c.tertiary })
hi("@function",           { fg = c.primary })
hi("@function.builtin",   { fg = c.primary,   italic = true })
hi("@keyword",            { fg = c.primary,   bold = true })
hi("@string",             { fg = c.secondary })
hi("@comment",            { fg = c.outline,   italic = true })
hi("@type",               { fg = c.tertiary })
hi("@type.builtin",       { fg = c.tertiary,  italic = true })
hi("@constant",           { fg = c.tertiary })
hi("@constant.builtin",   { fg = c.tertiary,  bold = true })
hi("@punctuation",        { fg = c.fg_muted })
hi("@operator",           { fg = c.fg_muted })
